### ISSUE TITLE
When Box indicator is turned off, the Arrow indicator stays on the screen

### ISSUE THREAD

**Issue by RenanLopes77** [jinincarnate/off-screen-indicator#1]
When the area is off from the screen:
![image](https://user-images.githubusercontent.com/32716671/83633602-981dc300-a577-11ea-9851-0321c7d1006d.png)

When the area is on the screen:
![image](https://user-images.githubusercontent.com/32716671/83633708-c6030780-a577-11ea-931d-3a30a42bb609.png)

Now the area with box indicator turned on:
![image](https://user-images.githubusercontent.com/32716671/83633844-f64aa600-a577-11ea-90cc-726a0ce12a7f.png)

So, for some reason when the box indicator is turned off the arrow indicator keeps the direction, but doesn't dissapear when the target object is being show.

**Comment by RenanLopes77** [comment]
Hey @jinincarnate, I fixed this issue, but I can't make a new pull request.
Long story short: I added a new indicator type (IndicatorType.NULL) and when target is on screen the arrow is deactivated.

**Comment by jinincarnate** [comment]
Hi @RenanLopes77 ,

Thanks for pointing this issue. I have tried to solve this issue similar to what you might have done. Please take a look if it solves your problem and we can close this issue. I haven't configured the project for pull request yet, will do it soon.
